# Generated by Django 6.0.6 on 2026-06-17 20:56

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
