# Generated by Django 6.0.6 on 2026-06-17 21:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_embedding_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
