# Generated by Django 6.0.6 on 2026-06-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question_text',
            new_name='question_text_en',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_ar',
            field=models.CharField(default='hh', max_length=255),
            preserve_default=False,
        ),
    ]
