# Generated by Django 6.0.6 on 2026-06-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitivelog',
            name='calculation_note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cognitivelog',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cognitivelog',
            name='quiz_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='cognitivelog',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
