# Generated by Django 6.0.6 on 2026-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cognitive_cost',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('postponed', 'Postponed'), ('overridden', 'Overridden')], default='pending', max_length=15),
        ),
    ]
