# Generated by Django 6.0.6 on 2026-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_agentmemory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='cognitive_cost',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('postponed', 'Postponed'), ('overridden', 'Overridden')], default='allowed', max_length=15),
        ),
    ]
