# Generated by Django 6.0.6 on 2026-06-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_cognitive_cost_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
