# Generated by Django 6.0.6 on 2026-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_title_task_name_task_cognitive_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(default='user_added', max_length=20),
        ),
    ]
