# Generated by Django 6.0.6 on 2026-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deadline_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('overridden', 'Overridden')], default='pending', max_length=15),
        ),
    ]
